---
service-one-griffin:
  chartRoot: charts/service-one
  file: values-do-griffin.yaml
service-one-hydra:
  chartRoot: charts/service-one
  file: values-do-hydra.yaml
service-one-kraken:
  chartRoot: charts/service-one
  file: values-do-kraken.yaml
service-one-phoenix:
  chartRoot: charts/service-one
  file: values-do-phoenix.yaml
service-one-loadtesting:
  chartRoot: charts/service-one
  file: values-lt.yaml

service-two-griffin:
  chartRoot: charts/service-two
  file: values-do-griffin.yaml
service-two-hydra:
  chartRoot: charts/service-two
  file: values-do-hydra.yaml
service-two-kraken:
  chartRoot: charts/service-two
  file: values-do-kraken.yaml
service-two-phoenix:
  chartRoot: charts/service-two
  file: values-do-phoenix.yaml
service-two-loadtesting:
  chartRoot: charts/service-two
  file: values-lt.yaml
