name: loadtest-pipeline.yaml

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to copy latest service images'
        required: true
        default: 'phoenix'
        type: choice
        options:
        - phoenix
        - griffin
        - kraken
        - hydra
      
jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3

      - name: Log Inputs
        run: |
          echo environment: ${{ inputs.environment }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Automated pipeline
        id: application
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          pip install pyyaml
          pip install ruamel.yaml
          python -u pipeline/pipeline.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PERSONAL }}
          body: |
            Automated loadtest pipeline.
          branch: automated-pipeline
          delete-branch: true
          labels: loadtest-pipeline
          title: "[Pipeline] Loadtest"

        
