name: "pipeline/loadtesting"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to copy latest service images'
        required: true
        default: 'phoenix'
        type: choice
        options:
        - phoenix
        - griffin
        - kraken
        - hydra
      
jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Log Inputs
        run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ inputs.environment }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Automated pipeline
        id: application
        run: |
          pip install pyyaml
          pip install ruamel.yaml
          python -u pipeline/pipeline.py
        
